---
# yaml-language-server: $schema=https://schema.blue-build.org/module-v1.json

# systemd-config.yml — Enable and disable systemd services

type: systemd
system:
  enabled:
    - tailscaled.service
    - input-remapper.service
    - fstrim.timer
    - podman-auto-update.timer

  disabled: []
